-- Schema dell'albo d'oro: storico dei piazzamenti per stagione e competizione.
-- Eseguire una tantum sul DB (es. Supabase SQL editor).
--
-- La connessione usata da Claude Code verso questo DB è in sola lettura, quindi
-- questo script va lanciato manualmente.
--
-- La tabella è puramente storica: i crediti registrati qui sono già stati
-- accreditati a suo tempo (es. via admin_crediti), questa li archivia soltanto
-- per la bacheca pubblica. Popolata via SQL a mano, l'applicazione non scrive.

CREATE TYPE competizione_albo AS ENUM ('Campionato', 'Coppa');

CREATE TABLE IF NOT EXISTS albo_oro (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stagione         varchar NOT NULL,
    competizione     competizione_albo NOT NULL,
    -- NULL per il Campionato, che non ha fasi; testo libero per la Coppa
    -- ("Finale", "Girone A", ...), quindi senza un ordine cronologico
    -- ricavabile dal database: vedi l'ORDER BY in app/repositories/albo_oro.py.
    fase             varchar,
    squadra          varchar NOT NULL
                     REFERENCES squadra(nome) ON UPDATE CASCADE ON DELETE RESTRICT,
    posizione        smallint NOT NULL,
    crediti_generati integer NOT NULL DEFAULT 0
);

-- Una sola squadra per posizione, e una sola posizione per squadra, dentro la
-- stessa stagione/competizione/fase. COALESCE perché in SQL due NULL non sono
-- uguali fra loro, e senza il vincolo non coprirebbe le righe di Campionato.
CREATE UNIQUE INDEX IF NOT EXISTS ux_albo_oro_posizione
    ON albo_oro (stagione, competizione, COALESCE(fase, ''), posizione);

CREATE UNIQUE INDEX IF NOT EXISTS ux_albo_oro_squadra_fase
    ON albo_oro (stagione, competizione, COALESCE(fase, ''), squadra);

-- Per la ricerca dei piazzamenti di una singola squadra.
CREATE INDEX IF NOT EXISTS idx_albo_oro_squadra ON albo_oro (squadra);
