-- ============================================================================
-- giocatore_storico: da quando un giocatore appartiene alla squadra che ne
-- detiene il cartellino, e in quali squadre e' passato. Script unico,
-- idempotente, da lanciare in una transazione sola (es. Supabase SQL editor).
--
-- La connessione usata da Claude Code verso questo DB e' in sola lettura:
-- questo script va lanciato a mano o dall'assistente con conferma esplicita.
--
-- Si segue il detentore del cartellino, non squadra_att: un prestito non
-- sposta il giocatore da una rosa all'altra, un riscatto si'. La promozione
-- dalla Primavera in prima squadra apre una permanenza nuova nella stessa
-- squadra: il periodo in Primavera resta nello storico, chiuso.
--
-- Una riga per ogni permanenza: `al` NULL = ancora in rosa (una sola riga
-- aperta per giocatore), `dal` NULL = data di arrivo non ricostruibile, da
-- completare dalla pagina admin "Arrivi in rosa".
--
-- Gli orari seguono la convenzione del resto dell'app: ora italiana
-- "nominale" (NOW() AT TIME ZONE 'Europe/Rome') in una colonna timestamptz.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS giocatore_storico (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    giocatore integer NOT NULL REFERENCES giocatore(id) ON UPDATE CASCADE ON DELETE CASCADE,
    -- Senza FK su squadra: un cambio di nome e' gestito dal trigger (vedi
    -- sotto), e l'eliminazione di una squadra non deve essere bloccata dal
    -- suo storico.
    squadra   varchar NOT NULL,
    dal       timestamptz,
    al        timestamptz,
    -- 'automatico' (trigger, cambio di detentore), 'promozione' (trigger,
    -- dalla Primavera in prima squadra), 'asta' / 'scambio' / 'riscatto'
    -- (ricostruita dallo storico all'avvio), 'admin' (inserita a mano),
    -- NULL se ignota.
    fonte     varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_giocatore_storico_aperta
    ON giocatore_storico (giocatore) WHERE al IS NULL;

CREATE INDEX IF NOT EXISTS idx_giocatore_storico_giocatore
    ON giocatore_storico (giocatore);


-- Il trigger copre ogni punto che cambia il cartellino (Python, pg_cron,
-- script del draft) senza doverli toccare uno per uno.
CREATE OR REPLACE FUNCTION public.registra_cambio_detentore()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_ora timestamptz := NOW() AT TIME ZONE 'Europe/Rome';
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF NEW.detentore_cartellino IS NOT DISTINCT FROM OLD.detentore_cartellino THEN
            -- Stessa squadra: conta solo la promozione dalla Primavera.
            IF OLD.tipo_contratto = 'Primavera'
               AND NEW.tipo_contratto <> 'Primavera'
               AND NEW.detentore_cartellino IS NOT NULL
               AND NEW.detentore_cartellino <> 'Svincolato' THEN
                UPDATE giocatore_storico SET al = v_ora WHERE giocatore = NEW.id AND al IS NULL;
                INSERT INTO giocatore_storico (giocatore, squadra, dal, fonte)
                VALUES (NEW.id, NEW.detentore_cartellino, v_ora, 'promozione');
            END IF;
            RETURN NULL;
        END IF;

        -- Una squadra rinominata arriva qui per l'ON UPDATE CASCADE della FK
        -- giocatore -> squadra: il vecchio nome non esiste piu'. Non e' un
        -- trasferimento, la permanenza continua sotto il nome nuovo.
        IF OLD.detentore_cartellino IS NOT NULL
           AND NEW.detentore_cartellino IS NOT NULL
           AND NOT EXISTS (SELECT 1 FROM squadra WHERE nome = OLD.detentore_cartellino) THEN
            UPDATE giocatore_storico
            SET squadra = NEW.detentore_cartellino
            WHERE giocatore = NEW.id AND squadra = OLD.detentore_cartellino;
            RETURN NULL;
        END IF;

        UPDATE giocatore_storico SET al = v_ora WHERE giocatore = NEW.id AND al IS NULL;
    END IF;

    IF NEW.detentore_cartellino IS NOT NULL AND NEW.detentore_cartellino <> 'Svincolato' THEN
        INSERT INTO giocatore_storico (giocatore, squadra, dal, fonte)
        VALUES (NEW.id, NEW.detentore_cartellino, v_ora, 'automatico');
    END IF;

    RETURN NULL;
END;
$function$;

DROP TRIGGER IF EXISTS trg_giocatore_storico ON giocatore;
CREATE TRIGGER trg_giocatore_storico
    AFTER INSERT OR UPDATE OF detentore_cartellino, tipo_contratto ON giocatore
    FOR EACH ROW EXECUTE FUNCTION public.registra_cambio_detentore();


-- Ricostruzione delle permanenze in corso. Si scrive una data solo quando e'
-- certa: l'ultimo evento strutturato (asta conclusa, scambio accettato,
-- riscatto a fine prestito) che ha portato il giocatore alla squadra che ne
-- ha oggi il cartellino, senza nulla dopo che lo contraddica. Tutti gli altri
-- restano con `dal` NULL e si completano da admin.
--
-- Il riscatto di un diritto non esercitato non e' distinguibile da uno
-- esercitato (entrambi 'terminato'), ma nel primo caso il cartellino non e'
-- mai passato alla ricevente: per questo i riscatti valgono solo come
-- candidati, non per smentire un evento successivo.
--
-- Gli svincoli, prima delle aste in app, vivono solo nel testo dei movimenti:
-- una menzione del nome dopo la data candidata la rende incerta. Il confronto
-- sul testo qui serve solo a escludere, mai a stabilire una data.
WITH eventi AS (
    SELECT giocatore, squadra_vincente AS squadra, tempo_fine_asta AS quando, 'asta' AS fonte
    FROM asta WHERE stato = 'conclusa' AND squadra_vincente IS NOT NULL
    UNION ALL
    SELECT unnest(giocatori_offerti), squadra_destinataria, data_risposta, 'scambio'
    FROM scambio WHERE stato = 'accettato'
    UNION ALL
    SELECT unnest(giocatori_richiesti), squadra_proponente, data_risposta, 'scambio'
    FROM scambio WHERE stato = 'accettato'
    UNION ALL
    SELECT giocatore, squadra_ricevente, data_fine, 'riscatto'
    FROM prestito
    WHERE stato = 'terminato' AND tipo_prestito IN ('diritto_di_riscatto', 'obbligo_di_riscatto')
),
candidato AS (
    SELECT DISTINCT ON (g.id) g.id, g.nome, e.quando, e.fonte
    FROM giocatore g
    JOIN eventi e ON e.giocatore = g.id AND e.squadra = g.detentore_cartellino
    WHERE e.quando IS NOT NULL
    ORDER BY g.id, e.quando DESC
),
certo AS (
    SELECT c.* FROM candidato c
    WHERE NOT EXISTS (
            SELECT 1 FROM eventi e
            WHERE e.giocatore = c.id AND e.quando > c.quando AND e.fonte <> 'riscatto')
      AND NOT EXISTS (
            SELECT 1 FROM movimenti_squadra m
            WHERE m.data > c.quando::date
              AND strpos(lower(m.evento), 'svincol') > 0
              AND strpos(lower(m.evento), lower(c.nome)) > 0)
)
INSERT INTO giocatore_storico (giocatore, squadra, dal, fonte)
SELECT g.id, g.detentore_cartellino, c.quando, c.fonte
FROM giocatore g
LEFT JOIN certo c ON c.id = g.id
WHERE g.detentore_cartellino IS NOT NULL
  AND g.detentore_cartellino <> 'Svincolato'
  AND NOT EXISTS (SELECT 1 FROM giocatore_storico s WHERE s.giocatore = g.id AND s.al IS NULL);

COMMIT;
